version: '3.8'

services:
  backend:
    build: ./backened        # Ensure folder name is 'backend' (not 'backened')
    ports:
      - "3033:3033"
    depends_on:
      - db

  frontend:
    build: .                # Frontend code is assumed to be in the current folder (E:\budgetApp1\budget)
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budget_breeze
      MYSQL_USER: hafsa
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"          # MySQL default port
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
