

services:
  backend:
    build: ./server
    ports:
      - "3033:3033"
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budget_breeze
      MYSQL_USER: hafsa
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
